---
- name: check ssh daemon config
  become: yes
  command: /usr/sbin/sshd -t -f /etc/ssh/sshd_config

- name: restart ssh daemon
  become: yes
  service:
    name: "{{ ssh_daemon }}"
    state: restarted
...